# Generated by Django 2.1.3 on 2018-12-03 03:19

import Issue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField(blank=True)),
                ('myInput', models.TextField(blank=True)),
                ('myOutput', models.TextField(blank=True)),
                ('time', models.IntegerField(blank=True, default=1000)),
                ('memory', models.IntegerField(blank=True, default=256)),
                ('sampleInput', models.TextField(blank=True, default='')),
                ('sampleOutput', models.TextField(blank=True, default='')),
                ('standardInput', models.FileField(blank=True, upload_to=Issue.models.save_standard_input)),
                ('standardOutput', models.FileField(blank=True, upload_to=Issue.models.save_standard_output)),
                ('tips', models.TextField(blank=True)),
                ('probSource', models.CharField(blank=True, max_length=10)),
                ('classification', models.CharField(blank=True, max_length=10)),
                ('probAuthority', models.CharField(choices=[('公开', '公开'), ('隐藏', '隐藏')], default='公开', max_length=2)),
                ('weight', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemCode',
            fields=[
                ('userName', models.CharField(blank=True, max_length=30)),
                ('probID', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('runID', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, default='0', max_length=2)),
                ('time', models.IntegerField(blank=True, default=0)),
                ('memory', models.IntegerField(blank=True, default=0)),
                ('language', models.CharField(blank=True, choices=[('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python')], default='C++', max_length=9)),
                ('subTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
