# Generated by Django 2.1 on 2018-12-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='no',
            field=models.IntegerField(auto_created=True, default=1000, primary_key=True, serialize=False),
        ),
    ]
