# Generated by Django 2.1 on 2019-03-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0002_auto_20181201_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
