# Generated by Django 2.1 on 2019-01-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0002_auto_20181201_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchlist',
            name='matchAuthority',
        ),
        migrations.AddField(
            model_name='matchregister',
            name='matchAuthority',
            field=models.CharField(blank=True, choices=[('允许', '允许'), ('禁止', '禁止')], default='允许', max_length=2),
        ),
    ]
